on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Create the tarball (artifact)
      - name: Create tarball
        run: |
          npm pack

      # Install JFrog CLI
      - name: Install JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          sudo mv jfrog /usr/local/bin/

      # Configure JFrog CLI with Artifactory credentials
      - name: JFrog CLI Configuration
        run: |
          jfrog rt config --url ${{ secrets.ARTIFACTORY_URL }} --user ${{ secrets.ARTIFACTORY_USER }} --password ${{ secrets.ARTIFACTORY_API_KEY }}

      # Upload the package to Artifactory
      - name: Upload artifact to Artifactory
        run: |
          curl -u ${{ secrets.ARTIFACTORY_USERNAME }}:${{ secrets.ARTIFACTORY_API_KEY }} \
          -X PUT "https://mycompany.jfrog.io/artifactory/npm-repo/my-node-app/1.0.0/nodejs-app-xray-test-1.0.0.tgz" \
          -T nodejs-app-xray-test-1.0.0.tgz

      # Trigger Xray scan on the uploaded artifact using the API
      - name: Trigger Xray Scan via API
        run: |
          curl -u ${{ secrets.ARTIFACTORY_USERNAME }}:${{ secrets.ARTIFACTORY_API_KEY }} \
          -X POST "https://mycompany.jfrog.io/artifactory/api/v1/scan/npm-repo/my-node-app/1.0.0/nodejs-app-xray-test-1.0.0.tgz"

      # Display Xray Scan Results
      - name: Display Xray Scan Results
        run: |
          curl -u ${{ secrets.ARTIFACTORY_USERNAME }}:${{ secrets.ARTIFACTORY_API_KEY }} \
          "https://mycompany.jfrog.io/artifactory/api/v1/scan-results/npm-repo/my-node-app/1.0.0/nodejs-app-xray-test-1.0.0.tgz"
